/**
 * ROS2 Docker Generator Core Logic
 * This file is shared between the CI (Node.js) and the Website (Browser).
 */

const ROS2_GENERATOR_CORE = {
    /**
     * Returns the official base image tag for a given distro and variant.
     */
    getBaseImage(distro, variant) {
        if (variant === 'ros-base' || variant === 'ros-core') {
            return `ros:${distro}-${variant}`;
        }
        // desktop-full is not an official OSRF image tag, fallback to desktop
        if (variant === 'desktop-full') {
            return `osrf/ros:${distro}-desktop`;
        }
        return `osrf/ros:${distro}-${variant}`;
    },

    /**
     * Maps internal package keys to actual apt package names for a given distro.
     */
    getRosPackages(distro, packages) {
        const map = {
            nav2: [`ros-${distro}-navigation2`, `ros-${distro}-nav2-bringup`],
            slam_toolbox: [`ros-${distro}-slam-toolbox`],
            cartographer: [`ros-${distro}-cartographer`, `ros-${distro}-cartographer-ros`],
            gazebo: distro === 'jazzy' || distro === 'kilted'
                ? [] // Gazebo Classic is EOL on Jazzy and newer (Ubuntu 24.04+)
                : [`ros-${distro}-gazebo-ros-pkgs`, `ros-${distro}-gazebo-ros2-control`],
            gz_sim: [`ros-${distro}-ros-gz`],
            rviz2: [`ros-${distro}-rviz2`, `ros-${distro}-rviz-common`],
            turtlebot3: distro === 'jazzy' || distro === 'kilted'
                ? [`ros-${distro}-turtlebot3`, `ros-${distro}-turtlebot3-msgs`]
                : [`ros-${distro}-turtlebot3`, `ros-${distro}-turtlebot3-msgs`, `ros-${distro}-turtlebot3-simulations`],
            moveit2: [`ros-${distro}-moveit`],
            ros2_control: [`ros-${distro}-ros2-control`, `ros-${distro}-ros2-controllers`],
            pcl: [`ros-${distro}-perception-pcl`, `ros-${distro}-pcl-ros`],
            cv_bridge: [`ros-${distro}-cv-bridge`, `ros-${distro}-image-transport`, `python3-opencv`],
            tf2: [`ros-${distro}-tf2-tools`, `ros-${distro}-tf-transformations`],
            cyclone_dds: [`ros-${distro}-rmw-cyclonedds-cpp`],
            rosbridge: [`ros-${distro}-rosbridge-suite`],
        };

        const result = [];
        packages.forEach(pkg => {
            // Skip special keys like 'cuda' and 'tensorrt' which are handled at the FROM / start level
            if (map[pkg] && pkg !== 'cuda' && pkg !== 'tensorrt') {
                result.push(...map[pkg]);
            }
        });
        return result.filter(Boolean);
    },

    /**
     * Generates a Dockerfile string based on the provided configuration.
     */
    buildDockerfile(config) {
        const {
            distro,
            variant,
            packages,
            tools,
            username,
            uid,
            workspace,
            userType
        } = config;

        const isRoot = userType === 'root';
        const ubuntuVersion = distro === 'humble' ? 'ubuntu22.04' : 'ubuntu24.04';
        const cudaVersion = distro === 'humble' ? '12.3.1' : '12.4.1';
        const hasCuda = packages.has('cuda') || packages.has('tensorrt');
        const baseImage = hasCuda
            ? `nvidia/cuda:${cudaVersion}-devel-${ubuntuVersion}`
            : this.getBaseImage(distro, variant);

        const lines = [];

        lines.push(`# =============================================================`);
        lines.push(`# ROS2 ${distro.charAt(0).toUpperCase() + distro.slice(1)} Dockerfile`);
        lines.push(`# Generated by ROS2 Docker Generator v1.0`);
        lines.push(`# =============================================================`);
        lines.push('');
        lines.push(`FROM ${baseImage}`);
        lines.push('');

        if (hasCuda) {
            lines.push(`# ── Install ROS2 on top of CUDA base ───────────────────────`);
            lines.push(`ENV DEBIAN_FRONTEND=noninteractive`);
            lines.push(`RUN apt-get update && apt-get install -y \\`);
            lines.push(`    curl gnupg2 lsb-release && \\`);
            lines.push(`    curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key \\`);
            lines.push(`    -o /usr/share/keyrings/ros-archive-keyring.gpg && \\`);
            lines.push(`    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] \\`);
            lines.push(`    http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" \\`);
            lines.push(`    > /etc/apt/sources.list.d/ros2.list && \\`);
            lines.push(`    apt-get update && apt-get install -y ros-${distro}-${variant} && \\`);
            lines.push(`    rm -rf /var/lib/apt/lists/*`);
            lines.push('');
        }

        lines.push(`ENV DEBIAN_FRONTEND=noninteractive`);
        lines.push(`SHELL ["/bin/bash", "-c"]`);
        lines.push('');

        // Handle desktop-full for non-CUDA images (osrf/ros only provides desktop)
        if (!hasCuda && variant === 'desktop-full') {
            lines.push(`# ── Upgrade to desktop-full ──────────────────────────────────`);
            lines.push(`RUN apt-get update && apt-get install -y \\`);
            lines.push(`    ros-${distro}-desktop-full && \\`);
            lines.push(`    rm -rf /var/lib/apt/lists/*`);
            lines.push('');
        }

        // Locale
        if (tools.has('locale')) {
            lines.push(`# ── Locale ──────────────────────────────────────────────────`);
            lines.push(`RUN apt-get update && apt-get install -y locales && \\`);
            lines.push(`    locale-gen en_US en_US.UTF-8 && \\`);
            lines.push(`    update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 && \\`);
            lines.push(`    rm -rf /var/lib/apt/lists/*`);
            lines.push(`ENV LANG=en_US.UTF-8`);
            lines.push('');
        }

        // System apt packages
        const aptPkgs = ['software-properties-common', 'apt-transport-https', 'ca-certificates'];
        if (tools.has('python3')) aptPkgs.push('python3', 'python3-pip', 'python3-venv', 'python3-setuptools');
        if (tools.has('git')) aptPkgs.push('git');
        if (tools.has('cmake')) aptPkgs.push('cmake', 'build-essential', 'gcc', 'g++');
        if (tools.has('nano')) aptPkgs.push('nano', 'vim');
        if (tools.has('tmux')) aptPkgs.push('tmux');
        if (tools.has('gdb')) aptPkgs.push('gdb', 'gdbserver');
        if (tools.has('net_tools')) aptPkgs.push('net-tools', 'iproute2', 'iputils-ping', 'curl', 'wget');
        if (tools.has('vcstool')) aptPkgs.push('python3-vcstool');
        if (tools.has('ssh')) aptPkgs.push('openssh-server');
        if (tools.has('x11')) aptPkgs.push('x11-apps', 'libx11-dev');
        if (!isRoot) aptPkgs.push('sudo');

        lines.push(`# ── System packages ─────────────────────────────────────────`);
        lines.push(`RUN apt-get update && apt-get install -y \\`);
        aptPkgs.forEach((p, i) => {
            lines.push(`    ${p}${i < aptPkgs.length - 1 ? ' \\' : ' \\'}`);
        });
        lines.push(`    && rm -rf /var/lib/apt/lists/*`);
        lines.push('');

        // ROS2 build tools
        const buildTools = [];
        if (tools.has('colcon')) buildTools.push('python3-colcon-common-extensions', 'python3-colcon-mixin');
        if (tools.has('rosdep')) buildTools.push('python3-rosdep');
        buildTools.push('python3-rosinstall-generator');

        if (buildTools.length > 0) {
            lines.push(`# ── ROS2 build tools ────────────────────────────────────────`);
            lines.push(`RUN apt-get update && apt-get install -y \\`);
            buildTools.forEach((p, i) => lines.push(`    ${p}${i < buildTools.length - 1 ? ' \\' : ' \\'}`));
            lines.push(`    && rm -rf /var/lib/apt/lists/*`);
            if (tools.has('rosdep')) {
                lines.push('');
                lines.push(`RUN rosdep init || true && rosdep update --rosdistro ${distro}`);
            }
            lines.push('');
        }

        // zsh
        if (tools.has('zsh')) {
            lines.push(`# ── Zsh + Oh-My-Zsh ─────────────────────────────────────────`);
            lines.push(`RUN apt-get update && apt-get install -y zsh && \\`);
            lines.push(`    rm -rf /var/lib/apt/lists/*`);
            lines.push(`RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended`);
            lines.push('');
        }

        // ROS2 packages
        const rosPkgs = this.getRosPackages(distro, packages);
        if (rosPkgs.length > 0) {
            lines.push(`# ── ROS2 packages ───────────────────────────────────────────`);
            lines.push(`RUN apt-get update && apt-get install -y \\`);
            rosPkgs.forEach((p, i) => lines.push(`    ${p}${i < rosPkgs.length - 1 ? ' \\' : ' \\'}`));
            lines.push(`    && rm -rf /var/lib/apt/lists/*`);
            lines.push('');
        }

        // CycloneDDS
        if (packages.has('cyclone_dds')) {
            lines.push(`# ── CycloneDDS as default RMW ───────────────────────────────`);
            lines.push(`ENV RMW_IMPLEMENTATION=rmw_cyclonedds_cpp`);
            lines.push('');
        }

        // TurtleBot3
        if (packages.has('turtlebot3')) {
            lines.push(`# ── TurtleBot3 model (burger / waffle / waffle_pi) ───────────`);
            lines.push(`ENV TURTLEBOT3_MODEL=waffle_pi`);
            lines.push('');
        }

        // SSH
        if (tools.has('ssh')) {
            lines.push(`# ── SSH server ────────────────────────────────────────────`);
            lines.push(`RUN mkdir /var/run/sshd && \\`);
            lines.push(`    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config`);
            lines.push(`EXPOSE 22`);
            lines.push('');
        }

        // User
        if (!isRoot) {
            lines.push(`# ── Non-root user ─────────────────────────────────────────`);
            lines.push(`ARG UID=${uid}`);
            lines.push(`ARG GID=${uid}`);
            lines.push(`RUN if getent group \${GID} >/dev/null; then \\`);
            lines.push(`        groupmod -n ${username} \$(getent group \${GID} | cut -d: -f1); \\`);
            lines.push(`    else \\`);
            lines.push(`        groupadd -g \${GID} ${username}; \\`);
            lines.push(`    fi && \\`);
            lines.push(`    if getent passwd \${UID} >/dev/null; then \\`);
            lines.push(`        usermod -l ${username} -m -d /home/${username} \$(getent passwd \${UID} | cut -d: -f1); \\`);
            lines.push(`    else \\`);
            lines.push(`        useradd -m -u \${UID} -g \${GID} -s /bin/bash ${username}; \\`);
            lines.push(`    fi`);
            if (tools.has('sudo')) {
                lines.push(`RUN echo "${username} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers`);
            }
            lines.push('');
            lines.push(`RUN mkdir -p ${workspace}/src && \\`);
            lines.push(`    chown -R ${username}:${username} ${workspace}`);
            lines.push('');
            lines.push(`USER ${username}`);
            lines.push(`WORKDIR ${workspace}`);
            lines.push('');
        } else {
            lines.push(`RUN mkdir -p ${workspace}/src`);
            lines.push(`WORKDIR ${workspace}`);
            lines.push('');
        }

        // Bashrc
        if (tools.has('bashrc')) {
            const homeDir = isRoot ? '/root' : `/home/${username}`;
            lines.push(`# ── Shell setup ───────────────────────────────────────────`);
            lines.push(`RUN echo "source /opt/ros/${distro}/setup.bash" >> ${homeDir}/.bashrc`);
            if (packages.has('cyclone_dds')) {
                lines.push(`RUN echo "export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp" >> ${homeDir}/.bashrc`);
            }
            if (packages.has('turtlebot3')) {
                lines.push(`RUN echo "export TURTLEBOT3_MODEL=waffle_pi" >> ${homeDir}/.bashrc`);
            }
            lines.push('');
        }

        // X11
        if (tools.has('x11')) {
            lines.push(`# ── X11 display forwarding ────────────────────────────────`);
            lines.push(`ENV DISPLAY=\${DISPLAY:-:0}`);
            lines.push(`ENV QT_X11_NO_MITSHM=1`);
            lines.push('');
        }

        // NVIDIA
        if (hasCuda) {
            lines.push(`# ── NVIDIA GPU runtime ──────────────────────────────────────`);
            lines.push(`ENV NVIDIA_VISIBLE_DEVICES=all`);
            lines.push(`ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics`);
            lines.push('');
        }

        lines.push(`CMD ["/bin/bash"]`);
        return lines.join('\n');
    },

    /**
     * Generates a docker-compose.yml string based on the provided configuration.
     */
    buildCompose(config) {
        const {
            distro,
            packages,
            tools,
            username,
            workspace,
            containerName,
            userType
        } = config;

        const isRoot = userType === 'root';
        const hasCuda = packages.has('cuda') || packages.has('tensorrt');
        const hasX11 = tools.has('x11');
        const hasSSH = tools.has('ssh');

        const lines = [];
        lines.push(`# docker-compose.yml — generated by ROS2 Docker Generator v1.0`);
        lines.push(`services:`);
        lines.push(`  ${containerName}:`);
        lines.push(`    build:`);
        lines.push(`      context: .`);
        lines.push(`      dockerfile: Dockerfile`);
        if (!isRoot) {
            lines.push(`      args:`);
            lines.push(`        UID: \${UID:-1000}`);
            lines.push(`        GID: \${GID:-1000}`);
        }
        lines.push(`    image: ros2-${distro}-${containerName}:latest`);
        lines.push(`    container_name: ${containerName}`);
        lines.push(`    hostname: ${containerName}`);
        lines.push(`    stdin_open: true`);
        lines.push(`    tty: true`);
        lines.push(`    restart: unless-stopped`);
        lines.push(`    network_mode: host`);
        lines.push(`    environment:`);
        lines.push(`      - ROS_DISTRO=${distro}`);
        if (hasX11) {
            lines.push(`      - DISPLAY=\${DISPLAY:-:0}`);
            lines.push(`      - QT_X11_NO_MITSHM=1`);
        }
        if (packages.has('cyclone_dds')) lines.push(`      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp`);
        if (packages.has('turtlebot3')) lines.push(`      - TURTLEBOT3_MODEL=waffle_pi`);
        lines.push(`    volumes:`);
        lines.push(`      - ./ros2_ws:${workspace}:rw`);
        if (hasX11) {
            lines.push(`      - /tmp/.X11-unix:/tmp/.X11-unix:rw`);
        }
        if (hasCuda) {
            lines.push(`    deploy:`);
            lines.push(`      resources:`);
            lines.push(`        reservations:`);
            lines.push(`          devices:`);
            lines.push(`            - driver: nvidia`);
            lines.push(`              count: all`);
            lines.push(`              capabilities: [gpu, compute, utility]`);
        }
        if (hasSSH) {
            lines.push(`    ports:`);
            lines.push(`      - "2222:22"`);
        }
        return lines.join('\n');
    },

    /**
     * Generates a README.md string based on the provided configuration.
     */
    buildReadme(config) {
        const { distro, variant, packages, tools, username, workspace, containerName, userType } = config;
        const u = userType === 'root' ? 'root' : username;
        const pkgList = [...packages].join(', ') || 'none';
        const toolList = [...tools].join(', ');

        return `# ROS2 ${distro.charAt(0).toUpperCase() + distro.slice(1)} Docker Environment

Generated by [ROS2 Docker Generator v1.0]

## What's Inside

- **ROS2 Distro**: ${distro} (${variant})
- **Packages**: ${pkgList}
- **Dev Tools**: ${toolList}
- **User**: ${u}
- **Workspace**: ${workspace}

## Prerequisites

1. **Docker Desktop**
2. **WSL2** (Windows)
3. **X Server** (for GUI apps)

## Quick Start

\`\`\`bash
# 1. Build the image
docker compose build

# 2. Start the container
docker compose up -d

# 3. Open a shell
docker exec -it ${containerName} bash

# 4. Inside the container — build your workspace
cd ${workspace}
colcon build --symlink-install
source install/setup.bash

# 5. Stop the container
docker compose down
\`\`\`

---
*Generated by ROS2 Docker Generator v1.0 Portfolio Tool*
`;
    }
};

// Export for Node.js if applicable
if (typeof module !== 'undefined' && module.exports) {
    module.exports = ROS2_GENERATOR_CORE;
}
