services:
  ros2-humble:
    build:
      context: .
      dockerfile: Dockerfile
    image: ros2-humble-playground:latest
    container_name: ros2_playground
    network_mode: host
    ipc: host
    privileged: true
    shm_size: '2gb'
    environment:
      - DISPLAY=host.docker.internal:0.0
      - TURTLEBOT3_MODEL=burger
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_SOFTWARE=1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./src:/home/rosuser/ros2_ws/src:rw
    stdin_open: true
    tty: true
    command: bash
