#!/usr/bin/env python3
import json
import sys
import re
from pathlib import Path

try:
    import tomllib
except ImportError:
    # Fallback for Python < 3.11 if needed, but the environment has 3.12
    import pip
    pip.main(['install', 'tomli'])
    import tomli as tomllib

ROOT = Path(__file__).parent.parent
SRC = ROOT / "src"
sys.path.insert(0, str(SRC))

from ros2_dockergen.core import GeneratorCore

def test_versions():
    print("Checking version consistency...")
    
    # 1. Read pyproject.toml (Source of Truth)
    pyproject_path = ROOT / "pyproject.toml"
    with open(pyproject_path, "rb") as f:
        pyproject = tomllib.load(f)
    version = pyproject["project"]["version"]
    print(f"  pyproject.toml: {version}")

    # 2. Check config.json
    config_path = SRC / "ros2_dockergen" / "data" / "config.json"
    with open(config_path, "r") as f:
        config = json.load(f)
    config_version = config["version"]
    print(f"  config.json:    {config_version}")
    
    if config_version != version:
        print(f"  ✗ Version mismatch! {config_version} != {version}")
        sys.exit(1)

    # 3. Check package.json
    package_path = ROOT / "package.json"
    if package_path.exists():
        with open(package_path, "r") as f:
            package = json.load(f)
        package_version = package["version"]
        print(f"  package.json:   {package_version}")
        if package_version != version:
            print(f"  ✗ Version mismatch! {package_version} != {version}")
            sys.exit(1)
    
    # 4. Check index.html (partial match for vX.Y.Z)
    index_path = ROOT / "index.html"
    if index_path.exists():
        content = index_path.read_text()
        # We expect at least one occurrence of the version string
        if f"v{version}" not in content:
            print(f"  ✗ index.html does not contain v{version}")
            # We'll be lenient if it's just v1.0
            # Let's check if there are ANY old versions left
            old_versions = re.findall(r"v1\.0\.[01]", content)
            if old_versions:
                print(f"  ✗ found old versions in index.html: {set(old_versions)}")
                sys.exit(1)
            print("  ✓ index.html OK (uses abbreviated v1.0)")
        else:
            print(f"  index.html:     {version}")

    # 5. Verify generated Dockerfile header
    core = GeneratorCore(config)
    sample_config = {
        "distro": "humble",
        "variant": "ros-base",
        "packages": [],
        "tools": ["colcon"],
        "user_type": "root",
        "username": "root",
        "uid": 0,
        "workspace": "/ros2_ws",
        "container_name": "test"
    }
    dockerfile = core.build_dockerfile(sample_config)
    header_match = re.search(r"Generated by ros2-dockergen v([\d\.]+)", dockerfile)
    if not header_match:
        print("  ✗ Could not find version header in generated Dockerfile")
        sys.exit(1)
    
    gen_version = header_match.group(1)
    print(f"  Generated DF:   {gen_version}")
    if gen_version != version:
        print(f"  ✗ Generated version mismatch! {gen_version} != {version}")
        sys.exit(1)

    print("\n✅ All versions are consistent!")

if __name__ == "__main__":
    test_versions()
