#!/usr/bin/env python3
import json
import sys
import re
from pathlib import Path

ROOT = Path(__file__).parent.parent
SRC = ROOT / "src"
sys.path.insert(0, str(SRC))

from ros2_dockergen.core import GeneratorCore

def test_versions():
    print("Checking version consistency (Source of Truth: config.json)...")
    
    # 1. Read config.json (New Source of Truth)
    config_path = SRC / "ros2_dockergen" / "data" / "config.json"
    if not config_path.exists():
        print(f"  ✗ config.json not found at {config_path}")
        sys.exit(1)
        
    with open(config_path, "r") as f:
        config = json.load(f)
    version = config.get("version")
    if not version:
        print("  ✗ No version found in config.json")
        sys.exit(1)
    print(f"  config.json:      {version}")

    # 2. Check pyproject.toml (should be dynamic)
    pyproject_path = ROOT / "pyproject.toml"
    with open(pyproject_path, "r") as f:
        pyproject_content = f.read()
    
    if 'dynamic = ["version"]' not in pyproject_content:
        print("  ✗ pyproject.toml is not configured for dynamic versioning")
        sys.exit(1)
    if 'source = "regex"' not in pyproject_content or 'path = "src/ros2_dockergen/data/config.json"' not in pyproject_content:
        print("  ✗ pyproject.toml hatch-regex configuration is missing or incorrect")
        sys.exit(1)
    print(f"  pyproject.toml:   Dynamic")

    # 3. Check package.json (should match config.json)
    package_path = ROOT / "package.json"
    if package_path.exists():
        with open(package_path, "r") as f:
            package = json.load(f)
        package_version = package.get("version")
        print(f"  package.json:     {package_version}")
        if package_version != version:
            print(f"  ✗ Metadata mismatch! package.json={package_version} != config.json={version}")
            print("    Run ./tests/sync_version.py to fix this.")
            sys.exit(1)
    
    # 4. Check index.html dynamic logic and static versions
    index_path = ROOT / "index.html"
    if index_path.exists():
        content = index_path.read_text()
        if 'const ver = config.version ||' not in content:
            print("  ✗ index.html is missing dynamic version injection logic")
            sys.exit(1)
            
        # Check static versions have been correctly synced
        title_expected = f"<title>ROS2 Docker Generator v{version} — Get Robotics Running Fast</title>"
        js_expected = f'const ver = config.version || "{version}";'
        
        if title_expected not in content or js_expected not in content:
            print(f"  ✗ index.html has out-of-sync <title> or JS fallback! Expected v{version}.")
            print("    Run ./tests/sync_version.py to fix this.")
            sys.exit(1)
            
        # Verify all .app-version-text spans match the version
        static_mentions = re.findall(r'class="app-version-text"[^>]*>v([\d\.]+)<', content)
        if not static_mentions:
            print("  ✗ Could not find any .app-version-text elements in index.html to verify.")
            sys.exit(1)
            
        for found_version in static_mentions:
            if found_version != version:
                print(f"  ✗ index.html has stale static version 'v{found_version}'. Expected 'v{version}'.")
                print("    Run ./tests/sync_version.py to fix this.")
                sys.exit(1)
                
        print("  index.html:       Dynamic + Static strings in sync")

    # 5. Verify generated Dockerfile header
    core = GeneratorCore(config)
    sample_config = {
        "distro": "humble",
        "variant": "ros-base",
        "packages": [],
        "tools": ["colcon"],
        "user_type": "root",
        "username": "root",
        "uid": 0,
        "workspace": "/ros2_ws",
        "container_name": "test"
    }
    dockerfile = core.build_dockerfile(sample_config)
    header_match = re.search(r"Generated by ros2-dockergen v([\d\.]+)", dockerfile)
    if not header_match:
        print("  ✗ Could not find version header in generated Dockerfile")
        sys.exit(1)
    
    gen_version = header_match.group(1)
    print(f"  Generated DF:     {gen_version}")
    if gen_version != version:
        print(f"  ✗ Generated version mismatch! v{gen_version} != v{version}")
        sys.exit(1)

    print("\nAll versions are consistent or are dynamic!")

if __name__ == "__main__":
    test_versions()
